#include "DummyTool.cpp"
#include "LoadFiles.cpp"
#include "Splitter.cpp"
#include "SplitLoop.cpp"
#include "Calibrate.cpp"
#include "RootOutput.cpp"
#include "PMTLocation.cpp"
#include "RunInformationCollector.cpp"
